# Generated by Django 2.0.4 on 2021-06-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_pt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='name_pt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='name_pt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_pt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='name_pt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
