# Generated by Django 2.0.4 on 2021-06-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss_app', '0002_auto_20210629_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_pt',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='description_pt',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='description_pt',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_pt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='description_pt',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description_pt',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='description_pt',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
