# Generated by Django 2.0.4 on 2022-01-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss_app', '0003_auto_20210629_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_ar',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='description_ar',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='name_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='description_ar',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='description_ar',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='name_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description_ar',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='description_ar',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='name_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
